title: Shefers Sarkar
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Systems Analyst 
  <br><br>
  Data Scientist  
  <br><br>
  <a href="https://www.linkedin.com/in/shefers-sarkar-a6587750/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
