title: Shefers Sarkar
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a highly motivated, agile, goal-oriented Analytics professional with IT and Human resource background.
  Focused on asking the right questions and delivering actionable insights.
  Experienced in Agile methodology, Advance/ad-hoc/automated reporting solutions, Enterprise Interface design and testing.
  Big believer in getting at the 'why' via ‘jobs to be done' theory.
  
  <br><br>
  
  <a href="https://www.linkedin.com/in/shefers-sarkar-a6587750/">View My LinkedIn Profile</a> 
  <br><br>
  theme: jekyll-theme-minimal
