title: Shefers Sarkar
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  **Critical Thinker**
  <br><br>
  <a href="https://www.linkedin.com/in/shefers-sarkar-a6587750/">View My LinkedIn Profile</a> 

theme: jekyll-theme-minimal
